# Generated by Django 5.0.6 on 2024-05-11 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=32)),
                ('cnpj', models.CharField(blank=True, max_length=64, null=True)),
                ('street', models.CharField(blank=True, max_length=64, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=64, null=True)),
                ('street_number', models.IntegerField(blank=True, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=64, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('industry', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=32)),
                ('cnpj', models.CharField(blank=True, max_length=64, null=True)),
                ('street', models.CharField(blank=True, max_length=64, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=64, null=True)),
                ('street_number', models.CharField(blank=True, max_length=64, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=64, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('industry', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=64, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payment_conditions', models.CharField(blank=True, max_length=256, null=True)),
                ('delivery_time', models.IntegerField(blank=True, null=True)),
                ('production_time', models.IntegerField(blank=True, null=True)),
                ('stock_consunption', models.IntegerField(blank=True, null=True)),
                ('commission', models.FloatField(blank=True, null=True)),
                ('fee', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=64)),
                ('product_slug', models.SlugField(blank=True, max_length=32)),
                ('portal_name', models.CharField(blank=True, max_length=64)),
                ('category', models.CharField(choices=[('Caixas rígidas', 'Caixas rígidas'), ('Papelaria', 'Papelaria'), ('Potes e copos', 'Potes e copos'), ('Adesivos e lacres', 'Adesivos e lacres'), ('Utensílios', 'Utensílios')], default='Sem categoria', max_length=100)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier')),
            ],
        ),
    ]
